import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 1500 }, deviceScaleFactor: 2 })
await p.goto('http://localhost:3000/instagram', { waitUntil: 'networkidle' })
await p.waitForTimeout(1500)
await p.getByText('Aztán jött a rend.', { exact: true }).first().click({ force: true })
await p.waitForTimeout(900)
await p.screenshot({ path: 'geo.png' })
await b.close()
console.log('done')
